name: Deploy to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is the branch the action will checkout
          ref: source

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: main
          # This is a common workaround for the "deploy from main to main" error
          # It allows the action to force push to the publish_branch
          force_orphan: true
